# Generated by Django 4.2.1 on 2023-05-12 23:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vk_id', models.PositiveIntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Queue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('people_limit', models.PositiveIntegerField(blank=True, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('current_position', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='QueueMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField()),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend_api.person')),
                ('queue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend_api.queue')),
            ],
        ),
        migrations.AddField(
            model_name='person',
            name='queues',
            field=models.ManyToManyField(through='backend_api.QueueMembership', to='backend_api.queue'),
        ),
    ]
