# Generated by Django 4.1.4 on 2023-05-15 21:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Queue',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('limit', models.PositiveIntegerField(blank=True, null=True)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('current_position', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='QueueUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(default=0)),
                ('is_admin', models.BooleanField(default=False)),
                ('on_queue', models.BooleanField(default=True)),
                ('queue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend_api.queue')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend_api.user')),
            ],
        ),
        migrations.AddField(
            model_name='queue',
            name='users',
            field=models.ManyToManyField(related_name='queues', through='backend_api.QueueUser', to='backend_api.user'),
        ),
    ]
