# Generated by Django 4.1.4 on 2023-05-13 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vk_id', models.BigIntegerField(unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='queuemembership',
            name='person',
        ),
        migrations.RemoveField(
            model_name='queuemembership',
            name='queue',
        ),
        migrations.RenameField(
            model_name='queue',
            old_name='people_limit',
            new_name='limit',
        ),
        migrations.AlterField(
            model_name='queue',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='queue',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='queue',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='queue',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Person',
        ),
        migrations.DeleteModel(
            name='QueueMembership',
        ),
        migrations.AddField(
            model_name='queue',
            name='participants',
            field=models.ManyToManyField(related_name='queues', to='backend_api.user'),
        ),
    ]
