# Generated by Django 4.1.4 on 2023-05-15 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='queueuser',
            options={'ordering': ['position']},
        ),
        migrations.AlterField(
            model_name='queueuser',
            name='position',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
