# Generated by Django 4.1.4 on 2023-05-13 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0002_user_remove_queuemembership_person_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='vk_id',
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
