# Generated by Django 4.1.4 on 2023-05-16 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0003_queue_creator_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='queueuser',
            name='on_queue',
        ),
        migrations.AlterField(
            model_name='queueuser',
            name='position',
            field=models.PositiveIntegerField(default=None),
        ),
    ]
