# Generated by Django 4.1.4 on 2023-05-13 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0003_remove_user_vk_id_alter_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='queue',
            old_name='participants',
            new_name='users',
        ),
    ]
