# Generated by Django 4.1.4 on 2023-05-16 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0004_remove_queueuser_on_queue_alter_queueuser_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queueuser',
            name='position',
            field=models.PositiveIntegerField(default=None, null=True),
        ),
    ]
